name: Label Checker
on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce PR Label
        id: enforce_pr_labels
        uses: amaldinesh7/enforce-pr-labels@main
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Example of message !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print output
        env:
          MESSAGE: ${{steps.enforce_pr_labels.outputs.message}}
        if: |
          always() && ${{env.MESSAGE != ''}}
        run: echo "${{steps.enforce_pr_labels.outputs.message}}"

    