name: "Publish"
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0 
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"  
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.2

      - name: Run Python
        id: PYTHON
        run: |
           results=$(echo "${{ steps.PR.outputs.pr_body }}" | python3 -c 'import sys; print(sys.stdin.read())')
          
           echo "$results"
           echo "-----"
           echp -e $results
           echo "::set-output name=pythonResult::$results"

  # python3 -c 'import sys; print(sys.stdin.read().partition('Description')[2].partition('### Checklist')[0].strip().replace('\n', '%0A')) 
      # - name: Extract changelog
      #   id: CHANGELOG
      #   uses: amaldinesh7/extract-substring@master
      #   with:
      #     content: ${{ steps.PR.outputs.pr_body }}
      #     delimiterOne: "Description"
      #     delimiterTwo: "### Checklist"
          
      - run: echo "-------"

      - run: echo "${{ steps.PYTHON.outputs.pythonResult }}"
