name: "Publish"
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0 
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"  
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}


      - name: Extract changelog
        id: CHANGELOG
        uses: amaldinesh7/extract-substring@master
        with:
          content: ${{ steps.PR.outputs.pr_body }}
          delimiterOne: "Description"
          delimiterTwo: "### Checklist"
          
      - run: echo "${{ steps.CHANGELOG.outputs.match }}"
