name: "Publish"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  release:
    name: "Release"
    runs-on: macos-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn config set version-tag-prefix "v"
      - run: yarn version --patch
      - run: git config core.hooksPath /dev/null
      - uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'New version release'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - if: contains(github.event.pull_request.labels.*.name, 'Release')  
        name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          # fromTag: ${{ steps.get-latest-tag.outputs.tag }}
          toTag: "v${{ steps.package-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - if: contains(github.event.pull_request.labels.*.name, 'Release')  
        name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{steps.github_release.outputs.changelog}}
          
      # - name: "Publish"
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     access: "public"
      #     token: ${{ secrets.NPM_TOKEN }}