name: "Publish"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  release:
    name: "Release"
    runs-on: macos-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name,'storybook') }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0 
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"  
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          
      - run: echo "Your PR is ${prBody}"
        env:
          prBody: ${{ steps.PR.outputs.pr_body }}

       
          
      # - name: "Publish"
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     access: "public"
      #     token: ${{ secrets.NPM_TOKEN }}
