name: "Publish"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  release:
    name: "Release"
    runs-on: macos-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name,'storybook') }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0 
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"  
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Extract changelog
        id: CHANGELOG
        run: |
          body=$(echo -e '${{ steps.PR.outputs.pr_body }}' | sed -n '/Description/{:a;N;/### Checklist/!ba;s/.*Description\|### Checklist.*//g;p}')
          echo "------"
          echo $body
          echo "------"
          echo "------"
          echo -e '${{ steps.PR.outputs.pr_body }}'
          echo "------"
          echo "::set-output name=CHANGELOG_BODY::$(echo $body)"
        shell: bash
          
      - run: echo ${{ steps.CHANGELOG.outputs.CHANGELOG_BODY }}

       
          
      # - name: "Publish"
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     access: "public"
      #     token: ${{ secrets.NPM_TOKEN }}
