name: Label Checker
on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce PR Label
        id: enforce_pr_labels
        uses: amaldinesh7/enforce-pr-labels@main
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"

      - name: Print output
        if: always()
        run: echo "${{steps.enforce_pr_labels.outputs.message}}"

    