name: "Create release notes"
on:
  workflow_run:
    workflows: ["Publish"]
    branches: [main]
    types:
      - completed
jobs:
  release:
    name: "Release notes"
    runs-on: macos-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}